apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-results-pvc
  namespace: test-automation
  labels:
    app: cucumber-test-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Uncomment and set for your cluster's storage class:
  # storageClassName: managed-nfs-storage
